version: "2"
run:
  build-tags:
    - codeanalysis
  tests: false
  relative-path-mode: gomod
linters:
  default: all
  disable:
    - depguard
    - funcorder
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - ireturn
    - mnd
    - nlreturn
    - nonamedreturns
    - protogetter
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    errorlint:
      errorf: false
    funlen:
      lines: 100
      statements: 60
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - ifElseChain
        - commentFormatting
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - shadow
    lll:
      line-length: 180
    misspell:
      locale: US
    revive:
      confidence: 0
      severity: error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - staticcheck
        text: 'SA1019: package github.com/golang/protobuf/proto is deprecated:'
    paths:
      - .*_?generated\.go
      - tests?/
      - pkg/pb/
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 100
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_?generated\.go
      - tests?/
      - pkg/pb/
      - third_party$
      - builtin$
      - examples$

