
name: golangci-lint-publish
on:
  release:
    types: [ published ]

jobs:
  build:
    env:
      registry_name: quay.io/mittwald/golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get image tags
        id: image_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ${{ env.registry_name }}:latest
            ${{ env.registry_name }}:${{ steps.image_tag.outputs.tag }}